services:
  db:
    image: postgres:13  
    container_name: cmmpostgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: CMMDB
    volumes:
      - ./data:/var/lib/postgresql/data  # Mapeamento do volume

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmmapp
    ports:
      - "5035:8080"  # Expondo a porta da aplicação
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=CMMDB;Username=usuario;Password=senha
    depends_on:
      - db